services:
  app:
    build:
      context: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - app-vendor:/var/www/html/vendor
    depends_on:
      - mysql

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - biblioteca-mysql:/var/lib/mysql

volumes:
  biblioteca-mysql:
  app-vendor:
